### ISSUE TITLE
Printing quallified type names (i.e., prefixing the output types with 'ast.')

### ISSUE THREAD

**Issue by stefanct** [asottile/astpretty#21]
I want to take the output of astpretty and stuff it back again into a program (manually), i.e. I am using astpretty to produce the python code that then produces the python program :D.
To that end, I would rather like to avoid importing * from ast and simply `import ast`.
With the current implementation of astpretty I need to add 'ast.' to all the `ast` types like `Subscript`, `Name` etc.

The change to always print these out is trivial: there are two places where adding `'ast.' + ` in fron of `type(node).__name__` does that, in `_leaf` (line 50) and the else path of `pformat` (line 93), respectively.
It might be worth it to make this configurable maybe...? I don't think it should be the default for brevity reasons... prints of ASTs are verbose enough already as you know ;)

**Comment by asottile** [comment]
`'ast.' +` isn't sufficient I'm afraid -- we also support `typed_ast` variants

would you like to propose an api to enable what you're asking for?  I don't want to change the current behaviour

**Comment by stefanct** [comment]
Not really TBH. I am fine with modifying my local copy since this is just for a tiny project with a clear EOL (uni course work). I just thought that it might be useful to others in similar situations (and in that case this ticket might already do the job). Feel free to continue with this issue as you see fit.

**Comment by asottile** [comment]
sounds good -- I'll probably leave it as is unless someone else has interest in picking this up

thanks for the issue and I'm glad it's helping you out with your project!
