### ISSUE TITLE
Allow using stdin for input

### ISSUE THREAD

**Issue by pradyunsg** [asottile/astpretty#26]
That'd let me do:

```
echo "assert (x:=0), x" | astpretty -
```

Which is much better than:

```
echo "assert (x:=0), x + 1" | python3.8 -c "import ast; print(ast.dump(ast.parse(input()), c))"
```

Of course, I ended up doing the following, which works -- but isn't as nice as doing it in one step. :)

```
echo "assert (x:=0), x" > /tmp/assert.py
astpretty /tmp/assert.py
```

**Comment by asottile** [comment]
does `astpretty /dev/stdin` work for you?

**Comment by DahlitzFlorian** [comment]
I really like the idea of piping strings into it the "unix" way. Let me work on it and submit a PR even if it's rejected in the end. Let's see if I can get this to work!
