### ISSUE TITLE
pprint support context fields like `lineno`?

### ISSUE THREAD

**Issue by yifanwu** [asottile/astpretty#71]
Hi there,

Thanks for creating and maintaining this useful library!

I recently ran into this error

```bash
  File "/Users/yifanwu/miniforge3/lib/python3.9/site-packages/astpretty.py", line 115, in pformat
    attr = getattr(node, field)
AttributeError: 'Import' object has no attribute 'lineno'
```

And I think it would be nice not to make optional entries like `lineno` a requirement. From a cursory glance this can be either hard coded (all the context info around line numbers) or blanket caught in a try/catch statement.

What do you think?

**Comment by yifanwu** [comment]
My use case is that I'm manually creating AST nodes (doing some transpilation) and I do not want to specify low level info such as lineno.

Here is a standalone example just to illustrate (it's a little silly to print here, but in my use case I do some modifications)

```python
import ast
from astpretty import pprint
e = ast.Expr(
    value=ast.Call(
        func=ast.Attribute(
            value=ast.Name(id="my_object", ctx=ast.Load()),
            attr="exit",
            ctx=ast.Load(),
        ),
        args=[],
        keywords=[],
    ),
)
pprint(e)
```

Note that other libs, such as `astor.to_source` would take this `e` here without erroring about lineno etc. So I think it's a valid usecase.

**Comment by asottile** [comment]
ah cool!  in that case I think you can use `pprint(e, show_offsets=False)` ?

**Comment by yifanwu** [comment]
Ah thank you! Exactly what I was looking for!
